spring:
  application:
    name: IW_Authentication_Service

keycloak:
  server-url: ${KEYCLOAK_SERVER_URL}
  realm: ${KEYCLOAK_REALM}
  client-id: ${KEYCLOAK_CLIENT_ID}
  client-secret: ${KEYCLOAK_CLIENT_SECRET}

user-service:
  url: ${USER_SERVICE_URL}

server:
  port: 8083
logging:
  level:
    logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG


